config/routes.rb
Rails.application.routes.draw do

  resources :images

namespace :api, defaults: { format: 'json'} do
    namespace :v1 do
  get 'users/search', to: 'users#search'
    resources :users
      post 'auth_user' => 'authentication#authenticate_user'

  end
end

namespace :api, defaults: { format: 'json'} do
    namespace :v1 do
  get 'categories/search', to: 'categories#search'
    resources :categories
      post 'auth_category' => 'authentication#authenticate_category'

  end
end

namespace :api, defaults: { format: 'json'} do
    namespace :v1 do
  get 'work_categories/search', to: 'work_categories#search'
    resources :work_categories
      post 'auth_work_category' => 'authentication#authenticate_work_category'

  end
end

namespace :api, defaults: { format: 'json'} do
    namespace :v1 do
  get 'works/search', to: 'works#search'
    resources :works
      post 'auth_work' => 'authentication#authenticate_work'

  end
end

namespace :api, defaults: { format: 'json'} do
    namespace :v1 do
  get 'images/search', to: 'images#search'
    resources :images
      post 'auth_image' => 'authentication#authenticate_image'

  end
end

  root to: 'pages#home'
  get 'about', to: 'pages#about'

  resources :works

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user
  has_many :work_categories
  has_many :categories, through: :work_categories
  validates :title, presence: true, length: { minimum:3, maximum:50 }
  validates :description, presence: true, length: { minimum:10, maximum:300 }
  validates :user_id, presence: true
end

app/controllers/api/v1/works_controller.rb
module Api
  module V1
    class WorksController < ApiController
    before_action :authenticate_request!
      def index
        render json: Work.all
      end
      def show
        work = Work.find_by(id:params[:id])
        if work
          render json: work
        else
          render json: {error: 'Work not found'}, status: 404
        end
      end
    end
  end
end

app/controllers/api/works_controller.rb
class Api::WorksController < ApiController

  def index
    render json: Work.all
  end

  def show
    work = Work.find_by(id: params[:id])
    if work
      render json: work
    else
      render json: { error: 'Work not found'}, status: 404
    end
  end

  def create
    work = Works.new(title: params[:title], description: params[:description])
    if work.save
      render json: work
    else
      render json: { error: 'Cannot create book' }, status: 404
    end
  end




  def search
    render json: Work.where('name LIKE ?', "%#{params[:name]}")
  end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:update, :edit, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @works = Work.paginate(page: params[:page], per_page: 5)
  end

  def new
    @work = Work.new
  end

  def edit
  end

  def create
    @work = Work.new(work_params)
    @work.user = current_user
    if @work.save
      flash[:success] = "New Work Was Successfully Created"
      redirect_to work_path(@work)
    else
      render 'new'
    end
  end

  def update
    if @work.update(work_params)
      flash[:success] = "Work was successfully updated"
      redirect_to work_path(@work)
    else
      render 'edit'
    end

  end

  def show
  end

  def destroy
    @work.destroy
    flash[:danger] = "Work was successfully deleted"
    redirect_to works_path
  end

  private
    def set_work
      @work = Work.find(params[:id])
    end
    def work_params
      params.require(:work).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      if current_user !=@work.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own work"
        redirect_to root_path
      end
    end


end

app/views/works/_form.html.erb
<%= render 'shared/errors', obj: @work %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@work, :html => {class: "form-horizontal", role: "form"})  do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of work", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
          </div>
          <div class="col-sm-8">
        <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of the work" %>
        </div>
        </div>
        <div class="form-group" >
          <div class="row">
            <div class="col-sm-offset-2 col-sm-8">
              <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="form-group" >
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn-primary btn-lg' %>
          </div>
        </div>
        <% end %>
        <div class="col-xs-4 col-xs-offset-4">
        [ <%= link_to "Cancel request and return to Work listing", works_path %> ]
          </div>
          </div>
        </div>

app/views/works/_work.html.erb
<% obj.each do |work| %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      <div class="work-title">
        <%= link_to work.title, work_path(work) %>
      </div>
      <div class="work-body">
        <%= truncate(work.description, length: 100) %></td>
        <div class="works-meta-details">
          <small>Created by: <%= work.user.username if work.user %>,
               <%= time_ago_in_words(work.created_at) %> ago,
               last updated: <%= time_ago_in_words(work.updated_at) %> ago</small>
        </div>
      </div>
      <% if work.categories.any? %>
        <p>Categories: <%= render work.categories %></p>
      <% end %>
      <% if logged_in? && (current_user == work.user || current_user.admin?) %>
        <div class="work-actions">
          <%= link_to "Edit this work", edit_work_path(work), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this Work", work_path(work), method: :delete,
                      data: {confirm: "Are you sure you want to delete this work?"},
                      class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/works/edit.html.erb
<h1 align="center">Edit Existing Work</h1>

<%= render 'form' %>

app/views/works/index.html.erb
<h1 align="center">Listing all Works</h1>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'work', obj: @works %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/works/new.html.erb
<h1 align="center">Post a new Work</h1>

<%= render 'form' %>

app/views/works/show.html.erb
<h2 align="center">Title: <%= @work.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <% if @work.user %>
    <ul class="listing">
    <div class="row center">
      <div class="col-md-4 col-md-offset-4">
        <li>Created by:</li>
        <li><%= link_to gravatar_for(@work.user), user_path(@work.user) %></li>
        <li class="work-title">
          <%= link_to @work.user.username, user_path(@work.user) %>
        </li>
        <li><small>
          <%= pluralize(@work.user.works.count, "work") if @work.user.works %>
        </small></li>
      </div>
    </div>
  </ul>
  <% end %>
  <h4 class="center description"><strong>Description</strong></h4>
  <hr>
  <%= simple_format(@work.description) %>
  <% if @work.categories.any? %>
   <p>Categories: <%= render @work.categories %></p>
  <% end %>
  <div class="work-actions">
    <% if logged_in? && (current_user == @work.user || current_user.admin?) %>
     <%= link_to "Edit this work", edit_work_path(@work), class: "btn btn-xs btn-primary" %>
     <%= link_to "Delete this Work", work_path(@work), method: :delete,
                data: {confirm: "Are you sure you want to delete this work?"},
                class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all created works", works_path, class: "btn btn-xs btn-success" %>
  </div>
</div>